import { pool } from "../config/db.js";

export async function listPayments(request, response, next) {
  try {
    const { tenantId, status } = request.query;
    const where = [];
    const values = [];

    if (tenantId) {
      values.push(tenantId);
      where.push(`tenant_id = $${values.length}`);
    }
    if (status) {
      values.push(status);
      where.push(`status = $${values.length}`);
    }

    const sql = `SELECT * FROM payments ${where.length ? `WHERE ${where.join(" AND ")}` : ""} ORDER BY month ASC`;
    const result = await pool.query(sql, values);
    response.json(result.rows);
  } catch (error) {
    next(error);
  }
}

export async function createMonthRangePayments(request, response, next) {
  try {
    const { tenant_id, months, default_amount } = request.body;
    const inserted = [];
    for (const month of months) {
      const row = await pool.query(
        `INSERT INTO payments(tenant_id, month, amount, status, notes)
         VALUES($1, $2, $3, 'unpaid', 'Generated by range')
         ON CONFLICT (tenant_id, month) DO NOTHING
         RETURNING *`,
        [tenant_id, month, default_amount]
      );
      if (row.rows[0]) {
        inserted.push(row.rows[0]);
      }
    }
    response.status(201).json(inserted);
  } catch (error) {
    next(error);
  }
}

export async function updatePayment(request, response, next) {
  try {
    const { id } = request.params;
    const { amount, status, payment_date, reference_no, notes } = request.body;
    const result = await pool.query(
      `UPDATE payments
       SET amount = $1, status = $2, payment_date = $3, reference_no = $4, notes = $5
       WHERE id = $6
       RETURNING *`,
      [amount, status, payment_date, reference_no, notes, id]
    );
    response.json(result.rows[0]);
  } catch (error) {
    next(error);
  }
}